### ISSUE TITLE
TerraformCLI - "show" does not work for Azure ApiManagement service

### ISSUE THREAD

**Issue by jesusArnas** [jason-johnson/azure-pipelines-tasks-terraform#156]
**Describe the bug**
TerraformCLI task with command "show" for a tfPlan file generates an error parsing JSON contents.

**To Reproduce**
1. Setup pipeline as (include yaml configuration or screenshots of classic ui editor)
```
- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
        displayName: Terraform plan
        inputs:
          command: plan
          commandOptions: '-detailed-exitcode -out=$(Pipeline.Workspace)/tfplan -input=false ${{ parameters.tfSecrets }}'
          workingDirectory: ${{ parameters.workingDirectory }}
          environmentServiceName: ${{ parameters.backendServicePrincipal }}
          publishPlanResults: ${{ parameters.artifactTfPlanName }}

- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
        displayName: Terraform show
        inputs:
          command: show
          environmentServiceName: ${{ parameters.backendServicePrincipal }}
          inputTargetPlanOrStateFilePath: $(Pipeline.Workspace)/tfplan
```
2. Execute pipeline
3. See error
##[error]SyntaxError: Unexpected end of JSON input

**Expected behavior**
TF show finishes and TERRAFORM_PLAN_HAS_DESTROY_CHANGES is set to "true"

**Agent Configuration**
 - OS:  ubuntu-20.04
 - Hosted
 - Terraform version used: 1.0.5
 - AzureCLI version used: default
 - Azurerm provider version used: 2.73.0

**Additional context**
Azure ApiManagement contains policies, that are xml contents. When "show" command is used, it creates blocks like this:
`"xml_content": "\u003cpolicies\u003e\r\n\t\u003cinbound\u003e\r\n\t\t\u003cquota-by-key calls=\"40\" renewal-period=\"3600\" counter-key=\"@(context.Request.IpAddress)\" ...",``
The regex used in tfShow task does not manage tabs and escaped double quotes, so JSON.parse throws an error.

A PR is linked with a test that reproduces the issue and a change at show task that fixes this problem #155

**Comment by jesusArnas** [comment]
#155 is the PR with the candidate solution

**Comment by tonylea** [comment]
I am experiencing this bug too. Using same agent config, except:

- Terraform version used: 1.0.6
-  Provider is PagerDuty, v1.10.1

**Comment by kasunsjc** [comment]
Me too having this issue creating AKS cluster and Postgres DBS

##[error]Terraform command 'show' failed with exit code '1'.
##[error]SyntaxError: Unexpected end of JSON input
##[error]SyntaxError: Unexpected end of JSON input

**Comment by charleszipp** [comment]
The issues with the ci pipeline that were preventing me from being able to accept @jesusArnas's contribution/fix have been resolved. The fix should be deployed with 0.6.28 this week . Apologies for the delays

**Comment by charleszipp** [comment]
the fix for this is available on the marketplace with 0.6.28

**Comment by kasunsjc** [comment]
@charleszipp Thank you :)  I have rewritten the full pipeline with terraform commands because of the error. Will use in future pipelines.

**Comment by RyanS-C** [comment]
I'm on version "0.6.28 (Latest)" and seem to still have this issue:
```

Starting: terraform show
==============================================================================
Task         : Terraform CLI
Description  : Execute terraform cli commands
Version      : 0.6.28
Author       : Charles Zipp
Help         : 
==============================================================================
/vsts_agents/agent1/_work/_tool/terraform/1.0.10/x64/terraform version
Terraform v1.0.10
on linux_amd64

##[error]Terraform command 'show' failed with exit code '1'.
##[error]SyntaxError: Unexpected end of JSON input
##[error]SyntaxError: Unexpected end of JSON input
Finishing: terraform show

```

**Comment by jesusArnas** [comment]
@RyanS-C , the issue could be the same, but a different cause. This error happens when a regex is applied to the tfShow result. 
What resource is being created / updated / deleted in that scenario?

**Comment by RyanS-C** [comment]
Thanks for replying.

the task is embedded within a pipeline template as follows:
```
parameters:
- name: terraformPlanOutputFile
  type: string

- task: TerraformCLI@0
  displayName: 'terraform show'
  inputs:
    command: show
    inputTargetPlanOrStateFilePath: '${{ parameters.terraformPlanOutputFile }}' 
```

The top level pipline parameter is fed in using:
```
- template: <Revoked>@templates
  parameters:
    agentPool: "<Revoked>"
    terraformProjectPath: <Revoked>
    terraformVersion: <Revoked>
    environmentServiceName: <Revoked>
    terraformWorkspace: "<Revoked>"
    terraformPlanFilePath: ./terraform.tfplan
```

In terms of what is changing this is an initial build for parsing the TF via CI build within Azure. It builds the infrastructure using the branch name for a number of resources. Once its created it will be destroyed.

one thing i have noticed is that I have the `-detailed-exitcode` enabled and I do get to see the plan in the Azure DevOps UI. So far the terraform itself is very basic and only has two resources as below:

```
# azurerm_key_vault.KeyVault will be created
  + resource "azurerm_key_vault" "KeyVault" {
      + access_policy               = (known after apply)
      + enabled_for_disk_encryption = true
      + id                          = (known after apply)
      + location                    = "westeurope"
      + name                        = "<Revoked>"
      + purge_protection_enabled    = false
      + resource_group_name         = "<Revoked>"
      + sku_name                    = "standard"
      + soft_delete_enabled         = (known after apply)
      + soft_delete_retention_days  = 30
      + tags                        = {
          + "BU"                 = "<Revoked>"
          + "CommitID"           = "<Revoked>"
          + "Product"            = "<Revoked>"
          + "TerraformWorkspace" = "<Revoked>"
        }
      + tenant_id                   = "<Revoked>"
      + vault_uri                   = (known after apply)

      + network_acls {
          + bypass                     = (known after apply)
          + default_action             = (known after apply)
          + ip_rules                   = (known after apply)
          + virtual_network_subnet_ids = (known after apply)
        }
    }

  # azurerm_resource_group.DPU will be created
  + resource "azurerm_resource_group" "DPU" {
      + id       = (known after apply)
      + location = "westeurope"
      + name     = "CI-initialterraform"
      + tags     = {
          + "BU"                 = "<Revoked>"
          + "CommitID"           = "<Revoked>"
          + "Product"            = "<Revoked>"
          + "TerraformWorkspace" = "<Revoked>"
        }
    }
```

**Comment by jesusArnas** [comment]
For me, it looks like a different scenario than the first one. The root cause in this bug was an issue with policies in ApiManagement,
I can't reproduce the bug with the given tfPlan. This is a summary that is printed in the console, but the complete plan is a bigger json with multiple nodes, and one of them is causing the reported error.
To identify the problematic node, try to follow these steps:
- After getting the tfPlan, upload it as a pipeline artifact
- Download it, and in your machine, you can perform a _terraform show_ command for the tfPlan (backend is not needed for that action)
- So, you can see full json contents. Try to identify special chars that could break a regex
- When the problematic node is found, open a new bug.

**Comment by gunacc** [comment]
Is there a fix available for this issue?
me too facing the same issue. See the error message which I got in my Azure pipelines,

2023-02-16T20:25:14.0310027Z ##[section]Starting: [Dev] Terraform : Show
2023-02-16T20:25:14.0318324Z ==============================================================================
2023-02-16T20:25:14.0318556Z Task         : Terraform CLI
2023-02-16T20:25:14.0318689Z Description  : Execute terraform cli commands
2023-02-16T20:25:14.0318856Z Version      : 0.7.8
2023-02-16T20:25:14.0318988Z Author       : Charles Zipp
2023-02-16T20:25:14.0319121Z Help         : 
2023-02-16T20:25:14.0319218Z ==============================================================================
2023-02-16T20:25:14.3845663Z [command]/opt/hostedtoolcache/terraform/1.3.9/x64/terraform version
2023-02-16T20:25:14.4196158Z Terraform v1.3.9
2023-02-16T20:25:14.4196670Z on linux_amd64
2023-02-16T20:25:14.4197120Z + provider registry.terraform.io/hashicorp/azurerm v3.43.0
2023-02-16T20:25:14.4197626Z + provider registry.terraform.io/hashicorp/random v3.4.3
2023-02-16T20:25:14.4728887Z ##[error]Terraform command 'show' failed with exit code '1'.
2023-02-16T20:25:14.4735026Z ##[error]SyntaxError: Unexpected end of JSON input
2023-02-16T20:25:14.4812078Z ##[error]SyntaxError: Unexpected end of JSON input
2023-02-16T20:25:14.5903751Z ##[section]Finishing: [Dev] Terraform : Show
